# -*- coding: utf-8 -*-
"""Timezone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wNw5yoCOYZYa-StU4cZ4MuaTJCWYpU5L
"""

import pandas as pd
import datetime
import pytz

"""# Timezone"""

datetime.datetime.utcnow()

datetime.datetime.now()

datetime.datetime.now(datetime.timezone.utc)

western = pytz.timezone('US/Pacific')
western.zone

"""## Localize the timezone"""

# method of localization
loc_dt = western.localize(datetime.datetime(2018, 5, 15, 12, 34, 0))

london_tz = pytz.timezone('Europe/London')
london_dt = loc_dt.astimezone(london_tz)
london_dt

f = '%Y-%m-%d %H:%M:%S %Z%z'
datetime.datetime(2018, 5, 12, 12, 15, 0, tzinfo=london_tz).strftime(f)

"""## Difference between datetime"""

# calculate the interval between wrong timezone
event1 = datetime.datetime(2018, 5, 12, 12, 15, 0, tzinfo=london_tz)
event2 = datetime.datetime(2018, 5, 13, 9, 15, 0, tzinfo=western)
event2 - event1

event1 = london_tz.localize(datetime.datetime(2018, 5, 12, 12, 15, 0))
event2 = western.localize(datetime.datetime(2018, 5, 13, 9, 15, 0))
event2 - event1

evenet1 = london_tz.localize(datetime.datetime(2018, 5, 12, 12, 15, 0)).astimezone(datetime.timezone.utc)
evenet2 = western.localize(datetime.datetime(2018, 5, 12, 12, 15, 0)).astimezone(datetime.timezone.utc)
event2 - event1

pytz.common_timezones

pytz.country_timezones('RU')

pytz.country_timezones('kr')

"""## Summer time"""

ambig_time = western.localize(datetime.datetime(2002, 10, 27, 1, 30, 00)).astimezone(datetime.timezone.utc)
ambig_time_earlier = ambig_time - datetime.timedelta(hours=1)
ambig_time_later = ambig_time + datetime.timedelta(hours=1)

display(ambig_time_earlier.astimezone(western))
display(ambig_time.astimezone(western))
display(ambig_time_later.astimezone(western))

"""We can see last two datetime is same.  
This is bad case. We need to change the data
"""

ambig_time = western.localize(datetime.datetime(2002, 10, 27, 1, 30, 00), is_dst=True)\
                                .astimezone(datetime.timezone.utc)
ambig_time_earlier = ambig_time - datetime.timedelta(hours=1)
ambig_time_later = ambig_time + datetime.timedelta(hours=1)

display(ambig_time_earlier.astimezone(western))
display(ambig_time.astimezone(western))
display(ambig_time_later.astimezone(western))