# -*- coding: utf-8 -*-
"""Smoothing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wib59M3bSmzkhnE70RHvRwzh-BtgNL2t
"""

import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['figure.figsize'] = (15,8)

air = pd.read_csv("./data/AirPassengers.csv", header=None)

air.columns = ['Date', 'Passengers']

print(air)

air['Smooth.5'] = air.ewm(alpha=0.5).mean().Passengers
air['Smooth.1'] = air.ewm(alpha=0.9).mean().Passengers

air['Date'] = pd.to_datetime(air['Date'], format='%Y-%m')

air

fig, ax = plt.subplots(1, 2 ,figsize=(22, 10))

sns.scatterplot(data=air, x='Date', y='Passengers', ax=ax[0])
sns.lineplot(data=air, x='Date', y='Passengers', ax=ax[1])

plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose

tmp = air.set_index('Date')
ts = tmp.Passengers
result = seasonal_decompose(ts, model='additive')


plt.rcParams['figure.figsize'] = [12, 8]
result.plot()
plt.show()